-- CCPM Installer
--
-- Applies resolved plans to disk and removes packages, keeping the record of which files each package owns.

-- MARK: Imports
local config = require("ccpm.config")
local files = require("ccpm.files")
local net = require("ccpm.net")
local paths = require("ccpm.paths")
local sha256 = require("ccpm.sha256")
local state = require("ccpm.state")

-- MARK: Constants
local SAFE_PATH_PATTERN = "^[%w%._/%-]+$"
local BIN_PATTERN = "^bin/[%w_%-]+%.lua$"
local STARTUP_PREFIX = "50_ccpm-"

-- MARK: Private Functions
--- Checks that an install path is safe and inside a location the package may write to, matching the registry's rules.
---@param name string The package name.
---@param path string The install path relative to the CCPM root.
---@return string|nil err A description of the problem, or `nil` if the path is allowed.
local function checkPath(name, path)
    -- Reject anything that could escape the CCPM root
    if not path:match(SAFE_PATH_PATTERN) then
        return "`" .. path .. "` is not a safe install path"
    end
    for segment in (path .. "/"):gmatch("([^/]*)/") do
        if segment == "" or segment == "." or segment == ".." then
            return "`" .. path .. "` is not a safe install path"
        end
    end

    -- Allow programs, the package's own library, and its own assets
    local top = path:match("^[^/]+")
    local inOwnFolder = path:sub(#top + 2, #top + #name + 2) == name .. "/"
    if (top == "bin" and path:match(BIN_PATTERN))
        or (top == "lib" and (path == "lib/" .. name .. ".lua" or inOwnFolder))
        or (top == "share" and inOwnFolder) then
        return nil
    end

    return "`" .. path .. "` is outside the folders " .. name .. " may install to"
end

--- Gets the absolute location of an install path.
---@param path string The install path relative to the CCPM root.
---@return string absolute The absolute path.
local function absolute(path)
    return paths.join(paths.root(), path)
end

--- Gets the boot file that runs a package's startup program.
---@param name string The package name.
---@return string path The absolute path.
local function startupPath(name)
    return paths.join(paths.startup(), STARTUP_PREFIX .. name:gsub("/", "-") .. ".lua")
end

--- Writes or removes a boot file that runs a program.
---@param name string The package or program name the boot file is for.
---@param program string|nil The absolute path of the program to run at boot, or `nil` to remove the boot file.
local function writeStartup(name, program)
    local path = startupPath(name)
    if not program then
        if fs.exists(path) then
            fs.delete(path)
        end
        return
    end

    files.write(path, "-- Generated by CCPM to start " .. name .. " at boot. Removing it with CCPM removes this file.\nshell.run(" .. string.format("%q", program) .. ")\n")
end

--- Deletes an installed file and any folders it leaves empty inside its top folder.
---@param path string The install path relative to the CCPM root.
local function deleteInstalled(path)
    files.deleteAndPrune(absolute(path), absolute(path:match("^[^/]+")))
end

--- Maps every installed file to the package that owns it.
---@return table<string, string> owners Package names keyed by install path.
local function fileOwners()
    local owners = {}
    for _, record in ipairs(state.list()) do
        for _, file in ipairs(record.files or {}) do
            owners[file.path] = record.name
        end
    end

    return owners
end

--- Downloads and checks every file of a plan step without writing anything.
---@param step PlanStep The step.
---@param owners table<string, string> Package names keyed by install path.
---@param force boolean|nil If unmanaged files may be overwritten.
---@return { path: string, sha256: string, data: string }[]|nil downloads The checked files, or `nil` if any check failed.
---@return string|nil err The error message if a check failed.
local function prepareStep(step, owners, force)
    local manifest = step.manifest
    if manifest.kind ~= "files" then
        return nil, step.name .. " uses the `" .. tostring(manifest.kind) .. "` kind, which this version of CCPM cannot install"
    end

    local downloads = {}
    for _, entry in ipairs(manifest.files or {}) do
        -- Check where the file goes
        local err = checkPath(step.name, entry.path)
        if err then
            return nil, step.name .. ": " .. err
        end
        local owner = owners[entry.path]
        if owner and owner ~= step.name then
            return nil, step.name .. " wants to install `" .. entry.path .. "`, which belongs to " .. owner
        end
        if not owner and fs.exists(absolute(entry.path)) and not force then
            return nil, step.name .. " wants to install `" .. entry.path .. "`, which already exists and is not managed by CCPM (use --force to overwrite it)"
        end

        -- Check where it comes from
        if not config.isAllowedUrl(entry.url, step.registry.hosts) then
            return nil, step.name .. ": `" .. entry.url .. "` is not on an allowed host (see `ccpm hosts`)"
        end

        -- Download and check its contents
        local data, downloadErr = net.get(entry.url)
        if not data then
            return nil, step.name .. ": " .. downloadErr
        end
        local actual = sha256.hex(data)
        if actual ~= entry.sha256 then
            return nil, step.name .. ": `" .. entry.path .. "` does not match its recorded hash, so it was not installed"
        end

        downloads[#downloads + 1] = { path = entry.path, sha256 = actual, data = data }
    end

    return downloads
end

--- Writes a prepared step to disk and records it.
---@param step PlanStep The step.
---@param downloads { path: string, sha256: string, data: string }[] The checked files.
local function commitStep(step, downloads)
    -- Write the new files
    local kept = {}
    for _, download in ipairs(downloads) do
        files.write(absolute(download.path), download.data)
        kept[download.path] = true
    end

    -- Remove files the previous version had that this one does not
    for _, file in ipairs(step.previous and step.previous.files or {}) do
        if not kept[file.path] then
            deleteInstalled(file.path)
        end
    end

    -- Start it at boot if asked
    writeStartup(step.name, step.manifest.startup and absolute(step.manifest.startup))

    -- Record it
    local recorded = {}
    for _, download in ipairs(downloads) do
        recorded[#recorded + 1] = { path = download.path, sha256 = download.sha256 }
    end
    state.put({
        name = step.name,
        version = step.version,
        registry = step.registry.name,
        kind = step.manifest.kind,
        files = recorded,
        dependencies = step.manifest.dependencies or {},
        startup = step.manifest.startup,
        explicit = step.explicit,
        range = step.range,
    })
end

--- Deletes an installed package's files, boot file, and record.
---@param record InstalledPackage The package's record.
local function uninstall(record)
    for _, file in ipairs(record.files or {}) do
        deleteInstalled(file.path)
    end
    writeStartup(record.name, nil)
    state.remove(record.name)
end

--- Removes dependencies that no installed package needs anymore.
---@return string[] removed The removed packages.
local function pruneOrphans()
    local removed = {}
    local removedOrphan = true
    while removedOrphan do
        removedOrphan = false
        for _, record in ipairs(state.list()) do
            if not record.explicit and #state.dependents(record.name) == 0 then
                uninstall(record)
                removed[#removed + 1] = record.name
                removedOrphan = true
            end
        end
    end

    return removed
end

-- MARK: Functions
local installer = {}

--- Gets the boot file that runs a package's startup program.
---@param name string The package name.
---@return string path The absolute path.
function installer.startupPath(name)
    return startupPath(name)
end

--- Writes or removes a boot file that runs a program, the same way packages with a startup program are started.
---@param name string The name the boot file is for.
---@param program string|nil The absolute path of the program to run at boot, or `nil` to remove the boot file.
function installer.setStartup(name, program)
    writeStartup(name, program)
end

--- Applies a plan, downloading and checking every file before changing anything on disk.
---@param plan Plan The plan.
---@param force boolean|nil If unmanaged files may be overwritten.
---@return string[]|nil removed Dependencies no longer needed and removed afterwards, or `nil` if the plan was not applied.
---@return string|nil err The error message if it was not applied.
function installer.apply(plan, force)
    -- Prepare every step first so a failure leaves the computer untouched
    local owners = fileOwners()
    local prepared = {}
    for i, step in ipairs(plan.steps) do
        local downloads, err = prepareStep(step, owners, force)
        if not downloads then
            return nil, err
        end
        prepared[i] = downloads
    end

    -- Commit them in dependency order
    for i, step in ipairs(plan.steps) do
        commitStep(step, prepared[i])
    end

    -- Remove dependencies the new versions dropped
    return pruneOrphans()
end

--- Removes packages, and the dependencies nothing else needs afterwards.
---@param names string[] The packages to remove.
---@param cascade boolean|nil If packages depending on them should be removed too, rather than refusing.
---@return string[]|nil removed Every package removed, or `nil` if nothing was removed.
---@return string|nil err The error message if nothing was removed.
function installer.remove(names, cascade)
    -- Collect the packages to remove
    local removing, order = {}, {}
    local function add(name)
        if not removing[name] then
            removing[name] = true
            order[#order + 1] = name
        end
    end
    for _, name in ipairs(names) do
        if not state.get(name) then
            return nil, name .. " is not installed"
        end
        add(name)
    end

    -- Refuse to break other packages unless cascading to them
    local i = 1
    while i <= #order do
        for _, dependent in ipairs(state.dependents(order[i])) do
            if not removing[dependent] then
                if not cascade then
                    return nil, order[i] .. " is needed by " .. dependent .. " (use --cascade to remove both)"
                end
                add(dependent)
            end
        end
        i = i + 1
    end

    -- Remove them
    for _, name in ipairs(order) do
        uninstall(assert(state.get(name)))
    end

    -- Remove dependencies that are no longer needed
    for _, name in ipairs(pruneOrphans()) do
        order[#order + 1] = name
    end

    return order
end

return installer
