-- CCPM Setup
--
-- Connects CCPM to the computer with a boot hook that adds installed programs to the shell path and completes `ccpm` commands.

-- CC: Tweaked builds every program's `require` path itself and offers no setting to extend it, so libraries are found through `require("/ccpm/lib/ccpm")` instead (see `init.lua`).

-- MARK: Imports
local files = require("ccpm.files")
local paths = require("ccpm.paths")

-- MARK: Constants
local HOOK_NAME = "00_ccpm.lua"
local PROGRAM = "bin/ccpm.lua"

-- MARK: Private Functions
--- Gets the source of the boot hook.
---@return string source The Lua source.
local function hookSource()
    local lib = paths.join(paths.lib(), "?.lua") .. ";" .. paths.join(paths.lib(), "?/init.lua") .. ";"
    return table.concat({
        "-- Generated by CCPM. Adds installed programs to the shell path and completes `ccpm` commands.",
        "local bin = " .. string.format("%q", paths.bin()),
        "if not (\":\" .. shell.path() .. \":\"):find(\":\" .. bin .. \":\", 1, true) then",
        "    shell.setPath(shell.path() .. \":\" .. bin)",
        "end",
        "package.path = " .. string.format("%q", lib) .. " .. package.path",
        "local ok, completion = pcall(require, \"ccpm.completion\")",
        "if ok then",
        "    shell.setCompletionFunction(" .. string.format("%q", fs.combine(paths.root(), PROGRAM)) .. ", completion.complete)",
        "end",
        "",
    }, "\n")
end

-- MARK: Functions
local setup = {}

--- Gets the path of the boot hook.
---@return string path The absolute path.
function setup.hookPath()
    return paths.join(paths.startup(), HOOK_NAME)
end

--- Checks if the boot hook is installed and current.
---@return boolean current If the hook exists with the expected contents.
function setup.isHookInstalled()
    return files.read(setup.hookPath()) == hookSource()
end

--- Installs the boot hook and applies it to the current shell.
---@param shellApi table|nil The running shell, to update without rebooting.
function setup.install(shellApi)
    files.write(setup.hookPath(), hookSource())

    -- Run the hook in this shell too, so completion comes from the installed libraries rather than wherever this code was loaded from
    if shellApi then
        shellApi.run(setup.hookPath())
    end
end

--- Removes the boot hook.
function setup.uninstall()
    if fs.exists(setup.hookPath()) then
        fs.delete(setup.hookPath())
    end
end

return setup
