-- CCPM Setup
--
-- Connects CCPM to the computer: the boot hook that adds installed programs to the shell path, and the `require` path for installed libraries.

-- MARK: Imports
local files = require("ccpm.files")
local paths = require("ccpm.paths")

-- MARK: Constants
local HOOK_NAME = "00_ccpm.lua"
local PACKAGE_PATH_SETTING = "shell.package_path"
local DEFAULT_PACKAGE_PATH = "?;?.lua;?/init.lua;/rom/modules/main/?;/rom/modules/main/?.lua;/rom/modules/main/?/init.lua"
local PROGRAM = "bin/ccpm.lua"

-- MARK: Private Functions
--- Gets the `require` patterns for installed libraries.
---@return string patterns The patterns, joined with `;`.
local function libraryPatterns()
    return paths.join(paths.lib(), "?.lua") .. ";" .. paths.join(paths.lib(), "?/init.lua")
end

--- Gets the source of the boot hook.
---@return string source The Lua source.
local function hookSource()
    return table.concat({
        "-- Generated by CCPM. Adds installed programs to the shell path and completes `ccpm` commands.",
        "local bin = " .. string.format("%q", paths.bin()),
        "if not (\":\" .. shell.path() .. \":\"):find(\":\" .. bin .. \":\", 1, true) then",
        "    shell.setPath(shell.path() .. \":\" .. bin)",
        "end",
        "package.path = " .. string.format("%q", libraryPatterns() .. ";") .. " .. package.path",
        "local ok, completion = pcall(require, \"ccpm.completion\")",
        "if ok then",
        "    shell.setCompletionFunction(" .. string.format("%q", fs.combine(paths.root(), PROGRAM)) .. ", completion.complete)",
        "end",
        "",
    }, "\n")
end

-- MARK: Functions
local setup = {}

--- Gets the path of the boot hook.
---@return string path The absolute path.
function setup.hookPath()
    return paths.join(paths.startup(), HOOK_NAME)
end

--- Checks if the boot hook is installed and current.
---@return boolean current If the hook exists with the expected contents.
function setup.isHookInstalled()
    return files.read(setup.hookPath()) == hookSource()
end

--- Checks if `require` finds installed libraries in every program.
---@return boolean configured If the package path setting includes the library folder.
function setup.isPackagePathConfigured()
    local current = settings.get(PACKAGE_PATH_SETTING) or ""
    return current:find(libraryPatterns(), 1, true) ~= nil
end

--- Installs the boot hook and the `require` path, and applies them to the current shell.
---@param shellApi table|nil The running shell, to update without rebooting.
function setup.install(shellApi)
    -- Write the boot hook
    files.write(setup.hookPath(), hookSource())

    -- Let every program require installed libraries
    if not setup.isPackagePathConfigured() then
        local current = settings.get(PACKAGE_PATH_SETTING) or DEFAULT_PACKAGE_PATH
        settings.set(PACKAGE_PATH_SETTING, current .. ";" .. libraryPatterns())
        settings.save()
    end

    -- Apply the hook to this shell too
    if shellApi then
        local bin = paths.bin()
        if not (":" .. shellApi.path() .. ":"):find(":" .. bin .. ":", 1, true) then
            shellApi.setPath(shellApi.path() .. ":" .. bin)
        end
        local ok, completion = pcall(require, "ccpm.completion")
        if ok then
            shellApi.setCompletionFunction(fs.combine(paths.root(), PROGRAM), completion.complete)
        end
    end
end

--- Removes the boot hook and the `require` path.
function setup.uninstall()
    if fs.exists(setup.hookPath()) then
        fs.delete(setup.hookPath())
    end

    -- Remove the library patterns from the setting
    local current = settings.get(PACKAGE_PATH_SETTING)
    if current then
        local start, finish = current:find(";" .. libraryPatterns(), 1, true)
        if start then
            settings.set(PACKAGE_PATH_SETTING, current:sub(1, start - 1) .. current:sub(finish + 1))
            settings.save()
        end
    end
end

return setup
